### ISSUE TITLE
Android 5.0版本，启动app时闪退

### ISSUE THREAD

**Issue by firehand33** [yangkun19921001/DexEncryptionDecryption#4]
在安卓5.0，启动app后就闪退了

react-native: 0.61.5

```
SUPPORTED_64_BIT_ABIS=[Ljava.lang.String;@7543702
versionCode=1
BOARD=unknown
BOOTLOADER=unknown
TYPE=userdebug
ID=LRX21M
TIME=1563224756000
BRAND=generic
TAG=Build
SERIAL=unknown
HARDWARE=goldfish
SUPPORTED_ABIS=[Ljava.lang.String;@152a3813
CPU_ABI=x86
IS_DEBUGGABLE=true
RADIO=unknown
MANUFACTURER=unknown
SUPPORTED_32_BIT_ABIS=[Ljava.lang.String;@ba2304d
TAGS=test-keys
CPU_ABI2=
UNKNOWN=unknown
USER=genymotion
FINGERPRINT=generic/vbox86p/vbox86p:5.0/LRX21M/392:userdebug/test-keys
HOST=f8dae71ced1e
PRODUCT=vbox86p
versionName=9.9.9
DISPLAY=vbox86p-userdebug 5.0 LRX21M 392 test-keys
MODEL=Google Nexus 5
DEVICE=vbox86p
java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{com.abc.jdcp.test/com.ttd.MainActivity}: java.lang.ClassNotFoundException: Didn't find class "com.ttd.MainActivity" on path: DexPathList[[zip file "/data/app/com.abc.jdcp.test-1/base.apk"],nativeLibraryDirectories=[/data/app/com.abc.jdcp.test-1/lib/x86, /vendor/lib, /system/lib]]
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2209)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2360)
	at android.app.ActivityThread.access$800(ActivityThread.java:144)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1278)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5221)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.ttd.MainActivity" on path: DexPathList[[zip file "/data/app/com.abc.jdcp.test-1/base.apk"],nativeLibraryDirectories=[/data/app/com.abc.jdcp.test-1/lib/x86, /vendor/lib, /system/lib]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
	at android.app.Instrumentation.newActivity(Instrumentation.java:1065)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2199)
	... 10 more
	Suppressed: java.lang.ClassNotFoundException: com.ttd.MainActivity
		at java.lang.Class.classForName(Native Method)
		at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
		at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
		at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
		... 13 more
	Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available
java.lang.ClassNotFoundException: Didn't find class "com.ttd.MainActivity" on path: DexPathList[[zip file "/data/app/com.abc.jdcp.test-1/base.apk"],nativeLibraryDirectories=[/data/app/com.abc.jdcp.test-1/lib/x86, /vendor/lib, /system/lib]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
	at android.app.Instrumentation.newActivity(Instrumentation.java:1065)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2199)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2360)
	at android.app.ActivityThread.access$800(ActivityThread.java:144)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1278)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5221)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
	Suppressed: java.lang.ClassNotFoundException: com.ttd.MainActivity
		at java.lang.Class.classForName(Native Method)
		at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
		at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
		at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
		... 13 more
	Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available

```

**Comment by yangkun19921001** [comment]
@firehand33 检查一下 MainActivity 是否经过 class -> dex ? 
根据错误日志来看，应该主 dex 加载找不到 MainActivityc.class
